In [2]:
from torch import nn
import torch

In [10]:

m = nn.Softmax(2, weights)
# you softmax over the 2nd dimension
input = torch.randn(2, 3, 12, 13)
output = m(input)

TypeError: Softmax.__init__() takes from 1 to 2 positional arguments but 3 were given

In [138]:
weights = torch.tensor([0.0001, 0.001, 0.002, 0.003, 0.004, 0.009, 0.01, 0.01, 0.04, 0.05, 0.12, 0.15, 0.2, 0.4009])

In [139]:
sum(weights)

tensor(1.)

In [35]:
output[0, :, 0, 0]

tensor([0.3213, 0.1263, 0.5523])

tensor(1.8679)

In [31]:
x = torch.randn(1, 2, 4)

In [32]:
x

tensor([[[ 1.0825,  1.3742,  0.9542,  0.4647],
         [ 1.1483, -1.4164,  0.0897,  0.3510]]])

In [35]:
y = x.view(1, 4, 2)

In [36]:
y

tensor([[[ 1.0825,  1.3742],
         [ 0.9542,  0.4647],
         [ 1.1483, -1.4164],
         [ 0.0897,  0.3510]]])

In [37]:
y.view(1, 2, 4)

tensor([[[ 1.0825,  1.3742,  0.9542,  0.4647],
         [ 1.1483, -1.4164,  0.0897,  0.3510]]])

In [38]:
t = torch.randn(1, 2, 4, 4)

In [39]:
t

tensor([[[[-1.2737,  0.5684, -0.1669, -0.8631],
          [ 1.3190, -1.2421, -1.1098,  0.0783],
          [-1.4254,  0.5533, -0.0481,  1.3027],
          [ 0.6334, -0.1179, -0.3327, -0.6344]],

         [[-0.2250, -0.6053,  1.1307, -0.5005],
          [ 0.2117, -0.2631,  0.3758, -1.2461],
          [ 0.3162,  1.3132, -0.2957, -0.1001],
          [ 0.2567,  0.3031,  0.2611, -1.9861]]]])

In [40]:
t.view(1, 4, 4, 2)

tensor([[[[-1.2737,  0.5684],
          [-0.1669, -0.8631],
          [ 1.3190, -1.2421],
          [-1.1098,  0.0783]],

         [[-1.4254,  0.5533],
          [-0.0481,  1.3027],
          [ 0.6334, -0.1179],
          [-0.3327, -0.6344]],

         [[-0.2250, -0.6053],
          [ 1.1307, -0.5005],
          [ 0.2117, -0.2631],
          [ 0.3758, -1.2461]],

         [[ 0.3162,  1.3132],
          [-0.2957, -0.1001],
          [ 0.2567,  0.3031],
          [ 0.2611, -1.9861]]]])

In [42]:
t[0, :, 1, 1]

tensor([-1.2421, -0.2631])

In [48]:
result = torch.argmax(output, 1)

In [49]:
result[0, 0, 0]

tensor(1)